### ISSUE TITLE
[BUG]: duplicate information on status bar

### ISSUE THREAD

**Issue by duard** [2KAbhishek/Dotfiles#6]
### Description of the bug

![image](https://user-images.githubusercontent.com/36894/220928176-c8dacf8a-e1bc-4daf-865a-2ffd8dc8bc50.png)

### Steps To Reproduce

I just try to install it

**Comment by duard** [comment]
I try to remove everthing and start again, but still showing duplicated information

**Comment by duard** [comment]
After remove and reinstall 

![image](https://user-images.githubusercontent.com/36894/220932093-b7471894-879e-4371-b2b6-c22d94c40b4f.png)

**Comment by duard** [comment]
Now it is working... but i has to remove all my .config folder and reinstall it.

**Comment by 2KAbhishek** [comment]
I am not sure what happened here, are you still facing the issue?

If possible can you share your tmux version, and output of the `neofetch` command

**Comment by 2KAbhishek** [comment]
closing till further updates
