### ISSUE TITLE
Auto push of Telekasten/.md notes upon save

### ISSUE THREAD

**Issue by artsbentley** [2KAbhishek/Dotfiles#7]
Hi, i recently watched your video with Josh on how you manage your dotfiles. I am very interested into how you commit and push telekasten/ markdown notes upon saving, could you link to the configuration for this setup?

**Comment by 2KAbhishek** [comment]
Hey, my bad that I couldn't reply earlier! I'm bad with github notifications.

For the syncing part I actually use a tool I wrote (a script actually) [committer](https://github.com/2KAbhishek/committer/)

I trigger the commit and sync using neovim, [config link](https://github.com/2KAbhishek/nvim2k/blob/c17b1763775b6e65f7d9be22720ac50375be2b38/lua/nvim2k/plugins/which-key.lua#L339) 

I also use [gsync](https://github.com/2KAbhishek/gsync) to have repos sync in the background at regular intervals

Let me know if you have more doubts
