### ISSUE TITLE
Question: 

### ISSUE THREAD

**Issue by paradigm-lab** [2KAbhishek/Dotfiles#9]
I am having a problem in creating the directory symbolic link `ln -sfnv "$PWD/.config/nvim" ~/.config/` because the directory exists.
I am getting `/home/{USERNAME}/.config/nvim: cannot overwrite directory` as an error will creating the symlink.
Also don't close the issue if you won't mind because I my have more questions please.

**Comment by 2KAbhishek** [comment]
You can simply delete/rename the nvim folder and run the command, or have it as part of your script as well

**Comment by 2KAbhishek** [comment]
Also I have opened up the discussion tab on this repo, If you have a question to ask please post here https://github.com/2KAbhishek/Dotfiles/discussions

**Comment by paradigm-lab** [comment]
Thanks 👍🙏, Got alot of questions And ideas 💡
